default:
    image: gradle:8.0.2-jdk17-alpine

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle
  - chmod +x gradlew



cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

stages:
    - build
    - test
    - deploy

test-app :
    stage: test
    script: 
        - echo "hello testing"
        - ./gradlew check --stacktrace

build-app :
  stage: build
  script:
    - ./gradlew assemble

deploy-app :
    stage: deploy
    script: 
        - echo "hello deploy"
        - ./deploy
