default:
    image: gradle:7.3.3-jdk17-alpine

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - chmod +x gradlew
  - export GRADLE_USER_HOME=`pwd`/.gradle

stages:
    - build
    - test
    - deploy

build-app :
  stage: build
  script:
    - sh gradlew assemble
  cache:
    paths:
    - .gradle/caches

test-app :
    stage: test
    script: 
        - echo "hello testing"
        - ./gradlew check --stacktrace


deploy-app :
    stage: deploy
    script: 
        - echo "hello deploy"
        - ./deploy
