
default:
    image: gradle:8.0.2-jdk17-alpine

variables:
    user: beb97

stages:
    - test
    - build
    - deploy

test-app :
    stage: test
    script: 
        - echo "hello testing"
        - ./gradlew check

build-app :
    stage: build
    script: 
        - echo "hello build"
        - ./gradlew build

deploy-app :
    stage: deploy
    script: echo "hello deploy"
